version: '3.8'

services:
  dashboard:
    build:
      context: ./painel
    container_name: dashboard
    ports:
      - "8000:8050"
    networks:
      - app_network
  etl:
    build:
      context: ./etl
    container_name: etl
    networks:
      - app_network
networks:
  app_network:
    driver: bridge