version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: sb-postgres
    environment:
      POSTGRES_USER: saude_basica
      POSTGRES_PASSWORD: saude_basica
      POSTGRES_DB: saude_basica
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_network
    deploy:
      resources:
        limits:
          cpus: "2.0"           # Limite de CPU
          memory: "2G"          # Limite de memória

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge
