version: '3.8'

services:
  dashboard:
    build:
      context: .
    container_name: dashboard
    ports:
      - "8000:8050"
    networks:
      - app_network
networks:
  app_network:
    driver: bridge