"""Módulo com funções auxiliares para o painel"""


def get_columns():
    """Função para retornar as colunas do DataFrame"""
    colunas = {
        "Problemas": [
            "Asma",
            "Desnutrição",
            "Diabetes",
            "DPOC",
            "Hipertensão arterial",
            "Obesidade",
            "Pré-natal",
            "Puericultura",
            "Puerpério (até 42 dias)",
            "Saúde sexual e reprodutiva",
            "Tabagismo",
            "Usuário de álcool",
            "Usuário de outras drogas",
            "Saúde mental",
            "Reabilitação",
            "D.Transmissíveis - Dengue",
            "Doenças transmissíveis - DST",
            "D.Transmissíveis - Hanseníase",
            "D.Transmissíveis - Tuberculose",
            "Rast. câncer de mama",
            "Rast. câncer do colo do útero",
            "Rast. risco cardiovascular",
        ],
        "Condutas Odontológicas": [
            "Agendamento p/ grupos",
            "Agendamento p/ outros profissi",
            "Encaminhamento - Cirurgia BMF",
            "Encaminhamento - Endodontia",
            "Encaminhamento - Estomatologia",
            "Encaminhamento - Implantodonti",
            "Encaminhamento - Odontopediatr",
            "Encaminhamento - Ortodontia/Or",
            "Encaminhamento - Outros",
            "Encaminhamento - Pacientes com",
            "Encaminhamento - Periodontia",
            "Encaminhamento - Prótese dentá",
            "Encaminhamento - Radiologia",
        ],
        "Condutas": [
            "Agendamento para grupos",
            "Encaminhamento interno no dia",
            "Encaminhamento intersetorial",
            "Encaminhamento p/ CAPS",
            "Encaminhamento p/ internação h",
            "Encaminhamento p/ serviço de a",
            "Encaminhamento p/ serviço espe",
            "Encaminhamento p/ urgência",
        ],
        "Procedimentos": [
            "Acuputura - ins. de agulhas",
            "Adm.  med. via endovenosa",
            "Adm.  med. via intramuscular",
            "Adm. Med. inalação/nebulização",
            "Adm. Med. via tópica",
            "Adm. med. via Subcutânea (SC)",
            "Adm. med. via oral",
            "Adm. penicilina p/ tto sífilis",
            "Caut. química pequenas lesões",
            "Cir. de unha (cantoplastia)",
            "Col. de cito. De colo uterino",
            "Col. mat. p/ ex. laboratorial",
            "Exérese/biopsia/punção de tum.",
            "Fundoscopia",
            "Infiltração em cav. sinovial",
            "Rem. Corp. Estranho Subcutâneo",
            "Rm. C. Est. Cav Auditiva/Nasal",
            "TERAPIA DE REIDRATACAO ORAL",
            "Tes. Ráp. p/ dosg. proteinúria",
        ],
        "Motivo Visita": [
            "Acomp.  Domiciliados/Acamados",
            "Acomp.  Pessoa c/ Diabetes",
            "Acomp.  Pessoa c/ Hanseníase",
            "Acomp.  Pessoa c/ Tuberculose",
            "Acomp.  Pessoas c/ D. Crônicas",
            "Acomp.  Recém-nascido",
            "Acomp. -  DPOC/Enfisema",
            "Acomp. - Usuário de drogas",
            "Acomp. Cond.  Bolsa Família",
            "Acomp. Condições de V.S.",
            "Acomp. PCD  ou reabilitação",
            "Acomp. Pessoa c/ Asma",
            "Acomp. Pessoa c/ Câncer",
            "Acomp. Pessoa c/ Desnutrição",
            "Acomp. Pessoa c/ Hipertensão",
            "Acomp. Sintomáticos Resp.",
            "Acomp. Usuário de álcool",
            "Acompanhamento - Criança",
            "Acompanhamento - Gestante",
            "Acompanhamento - Puérpera",
            "Acompanhamento - Saúde mental",
            "Acompanhamento - Tabagista",
            "B.A. - Cond.  Bolsa Família",
            "Busca ativa - Consulta",
            "Busca ativa - Exame",
            "Cadastramento/Atualização",
            "Controle de Ambientes/Vetores",
            "Convite At.Col./Camp. Saúde",
            "Egresso de Internação",
            "Outros",
        ],
    }

    return colunas
