version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8001:8001"
    networks:
      - app_network
    depends_on:
      - database
    environment:
      - DATABASE_URL=mongodb://database:27017/sisab_v2

  database:
    build:
      context: ./database
    container_name: database
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./database/data:/data/db
    environment:
      MONGO_INITDB_DATABASE: sisab_v2
    command: >
      bash -c "
      mongod --fork --logpath /var/log/mongodb.log --bind_ip_all &&
      mongorestore --gzip --archive=/data/db/sisab_v2.tar.gz &&
      mongod --shutdown &&
      mongod --bind_ip_all
      "

    networks:
      - app_network

  dashboard:
    build:
      context: ./dashboard
    container_name: dashboard
    ports:
      - "8000:8000"
    networks:
      - app_network
    depends_on:
      - backend
    environment:
      - DATABASE_URL=mongodb://database:27017/sisab_v2

  redis:
    build:
      context: ./redis  # Caminho para o Dockerfile (se estiver usando um)
    image: redis:latest  # Pode ser omitido se estiver usando um Dockerfile
    container_name: redis-server
    ports:
      - "6379:6379"  # Mapeia a porta 6379 do contêiner para a 6379 do host
    networks:
      - app_network
    volumes:
      - redis_data:/data  # Volume para persistir dados do Redis

networks:
  app_network:
    driver: bridge
