# Generated by Django 5.0.4 on 2024-09-07 20:31

import django.contrib.postgres.fields.hstore
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataImportCategory",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update date"),
                ),
                (
                    "name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("description", models.TextField()),
            ],
            options={
                "db_table": "data_import_category",
            },
        ),
        migrations.CreateModel(
            name="GeoUnitType",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update date"),
                ),
                (
                    "name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("description", models.TextField()),
            ],
            options={
                "db_table": "geo_unit_type",
            },
        ),
        migrations.CreateModel(
            name="DataImportProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update date"),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("active", models.BooleanField(default=True)),
                (
                    "data_import_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.dataimportcategory",
                    ),
                ),
            ],
            options={
                "db_table": "data_import_profile",
            },
        ),
        migrations.CreateModel(
            name="DataImportParam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update date"),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "value",
                    django.contrib.postgres.fields.hstore.HStoreField(
                        blank=True, null=True
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "data_import_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="params",
                        to="core.dataimportprofile",
                    ),
                ),
            ],
            options={
                "db_table": "data_import_param",
            },
        ),
        migrations.CreateModel(
            name="DataImportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("import_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("SUCCESS", "Success"), ("ERROR", "Error")],
                        default="SUCCESS",
                        max_length=50,
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "data_import_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.dataimportprofile",
                    ),
                ),
            ],
            options={
                "db_table": "data_import_log",
            },
        ),
        migrations.CreateModel(
            name="GeoUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update date"),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("altitude", models.FloatField(blank=True, null=True)),
                ("ibge", models.IntegerField(blank=True, null=True)),
                ("cnes", models.IntegerField(blank=True, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="core.geounit",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.geounittype",
                    ),
                ),
            ],
            options={
                "db_table": "geo_unit",
            },
        ),
        migrations.CreateModel(
            name="IndividualCare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update date"),
                ),
                ("group_param", models.CharField(max_length=255)),
                ("class_param", models.CharField(max_length=255)),
                ("ine", models.IntegerField(blank=True, null=True)),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                (
                    "geo_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.geounit"
                    ),
                ),
            ],
            options={
                "db_table": "individual_care",
            },
        ),
        migrations.CreateModel(
            name="IndividualCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update date"),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "individual_category",
                "indexes": [models.Index(fields=["name"], name="category_name_index")],
            },
        ),
        migrations.CreateModel(
            name="IndividualCareCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField()),
                (
                    "individual_care",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.individualcare",
                    ),
                ),
                (
                    "individual_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.individualcategory",
                    ),
                ),
            ],
            options={
                "db_table": "individual_care_category",
            },
        ),
        migrations.AddField(
            model_name="individualcare",
            name="individual_category",
            field=models.ManyToManyField(
                through="core.IndividualCareCategory", to="core.individualcategory"
            ),
        ),
        migrations.AddIndex(
            model_name="geounit",
            index=models.Index(fields=["name"], name="geo_unit_name_index"),
        ),
        migrations.AlterUniqueTogether(
            name="geounit",
            unique_together={("name", "parent")},
        ),
        migrations.AddConstraint(
            model_name="individualcarecategory",
            constraint=models.UniqueConstraint(
                fields=("individual_care", "individual_category"),
                name="unique_individual_care_category",
            ),
        ),
        migrations.AddIndex(
            model_name="individualcare",
            index=models.Index(fields=["year"], name="index_year"),
        ),
        migrations.AddIndex(
            model_name="individualcare",
            index=models.Index(fields=["year", "month"], name="index_year_month"),
        ),
    ]
