# Generated by Django 5.0.4 on 2024-10-10 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="individualcare",
            name="geo_unit_macro_region",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="individual_care_geo_unit_macro_region",
                to="core.geounit",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="individualcare",
            name="geo_unit_state",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="individual_care_geo_unit_state",
                to="core.geounit",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="individualcare",
            name="geo_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="individual_care_geo_unit",
                to="core.geounit",
            ),
        ),
    ]
