# Generated by Django 5.0.4 on 2024-10-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_individualcare_geo_unit_macro_region_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="individualcare",
            name="index_year_month",
        ),
        migrations.AddIndex(
            model_name="individualcare",
            index=models.Index(fields=["geo_unit"], name="index_geo_unit"),
        ),
        migrations.AddIndex(
            model_name="individualcare",
            index=models.Index(
                fields=["geo_unit_macro_region"],
                name="index_geo_unit_macro_region",
            ),
        ),
        migrations.AddIndex(
            model_name="individualcare",
            index=models.Index(
                fields=["geo_unit_state"], name="index_geo_unit_state"
            ),
        ),
        migrations.AddIndex(
            model_name="individualcare",
            index=models.Index(fields=["month"], name="index_month"),
        ),
    ]
